services:

  # db:
  #   image: mysql:9.2.0
  #   platform: linux/amd64
  #   container_name: mysql-db
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=mhasan123
  #     - MYSQL_DATABASE=simpleandroid_db
  #   ports:
  #     - "3307:3306"

  test-runner:
    build: .
    container_name: appium-test-runner
    # depends_on:
    #   - db
    environment:
      # - db.url=jdbc:mysql://db:3306/simpleandroid_db
      - db_url=${DB_URL}
      - db_user=${DB_USER}
      - db_password=${DB_PASSWORD}
      - appiumUrl=${APPIUM_URL}
      - HOST_PWD=${PWD}
      - TARGET_UDID=${TARGET_UDID}
      - TARGET_DEVICE_NAME=${TARGET_DEVICE_NAME}
      - TARGET_PLATFORM=${TARGET_PLATFORM}
      - TAGS=${TAGS}
    volumes:
      - ./allure-results:/app/allure-results
      - ./logs:/app/logs
      - maven-cache:/root/.m2
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  maven-cache:
