#data
appiumUrl=http://127.0.0.1:

#android
androidAutomationName=UiAutomator2
androidAppPackage=com.simpleapp
androidAppActivity=com.simpleapp.MainActivity
androidAppLocation=simple-app-testing.apk

#iOS
iOSAutomationName=XCUITest
iOSBundleId=org.reactjs.native.example.SimpleApp
iOSAppLocation=simple-app-testing.app

#Database
db.url=jdbc:mysql://localhost:3306/simpleandroid_db
db.user=mhasan
db.password=mhasan123
